#!/bin/bash

XRANDR_STATUS_FILE=/tmp/xrandr_last_status

touch $XRANDR_STATUS_FILE

#xrandr > $XRANDR_STATUS_FILE


DISPLAYS=(eDP-1 HDMI-1)

isConnected() {
    xrandr | grep -q "$1 connected"
}

current_status=""

for display in "${DISPLAYS[@]}"
do
    if isConnected $display 
    then
        current_status+="1"
    else
        current_status+="0"
    fi
done

previous_status=`cat $XRANDR_STATUS_FILE`
if [ $current_status != $previous_status ]
then
    echo "Different status"
fi

echo $current_status > $XRANDR_STATUS_FILE

